package com.adeeb.internify.model;

import java.util.List;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

public class MenuList {

    //Model generated by jsonschema2pojo.org!

    @SerializedName("menus")
    @Expose
    private List<Menu> menus = null;
    @SerializedName("pagination")
    @Expose
    private Pagination pagination;

    public List<Menu> getMenus() {
        return menus;
    }

    public void setMenus(List<Menu> menus) {
        this.menus = menus;
    }

    public Pagination getPagination() {
        return pagination;
    }

    public void setPagination(Pagination pagination) {
        this.pagination = pagination;
    }

}
